baseurl = "https://gucci-ninja.github.io/wordsandcode/"
languageCode = "en-us"
title = "Words & Code"
theme = "m10c"
paginate = 8
publishDir = "docs"
enableEmoji=true
googleAnalytics="UA-194918019-1"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "Suhavi Sandhu"
  description = "Software engineer passionate about building powerful, useful and open source systems. Thanks for dropping by! ðŸ’›"
  menu_item_separator = " - "
  avatar = "/wordsandcode/img/avatar.jpg"
  favicon = "https://pngimage.net/wp-content/uploads/2018/05/bullet-style-png-3-300x200.png"
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/gucci-ninja"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/SuhaviSandhu"
  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/suhavi/"
  googleAnalytics="UA-194918019-1"

  # Default theme
  [params.style]
   darkestColor = "#242930"
   darkColor = "#353b43"
   lightColor = "#afbac4"
   lightestColor = "#F4B648"
   primaryColor = "#F4B648"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

  # Red theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  lightColor = "#d6d6d6"
  #  lightestColor = "#d3d3d3"
  #  primaryColor = "#ffffff"
